### ISSUE TITLE
install.py exitsts with "Forge installation failed."

### ISSUE THREAD

**Issue by evschlenz** [cdbbnnyCode/modpack-installer#10]
install.py script first returns "Success!" and then aborts with "Forge installation failed.":
```
Injecting profile
Success!
Forge installation failed.
```
I used the command `python3 install.py "RLCraft 1.12.2 - Release v2.9.zip"` (Download [here](https://www.curseforge.com/minecraft/modpacks/rlcraft/download/3575903)) to run the install script. The modpack uses Forge version _1.12.2-forge-14.23.5.2860_, therefore is the expected version directory for this install _HOME/.minecraft/versions/1.12.2-forge-14.23.5.2860/_, which got created and linked correctly as a profile in the minecraft launcher, but the function `get_version_id(mcver, mlver)` in line 46 in the [forge installer script](https://github.com/cdbbnnyCode/modpack-installer/blob/master/forge_install.py#L46) returns `1.12.2-forge1.12.2-14.23.5.2860`. Because of that the check in line 41 in the [forge installer script](https://github.com/cdbbnnyCode/modpack-installer/blob/master/forge_install.py#L41) is False and stops the program.

I could recreate the same issue with [this](https://www.curseforge.com/minecraft/modpacks/all-the-mods-3/download/3348062) modpack, which uses Forge version _1.12.2-forge-14.23.5.2855_.

**Comment by cdbbnnyCode** [comment]
Hmm, it appears the Forge version system is being inconsistent; I will look into this.

**Comment by cdbbnnyCode** [comment]
Confirmed; newer 1.12.2 Forge releases are numbered differently.
![Screenshot_2022-01-11_08-49-56](https://user-images.githubusercontent.com/18408621/148965423-6934f5d2-215a-4fcb-bf41-94fab3020c8a.png)

**Comment by cdbbnnyCode** [comment]
Should be fixed in commit 2779baf.
