### ISSUE TITLE
(v2.2) Installer forgets symlinks when 504ing

### ISSUE THREAD

**Issue by krispr1ngle** [cdbbnnyCode/modpack-installer#12]
Whenever the installer 504s while checking for mods, upon checking the ones it first ran into the error on it seems to forget to create symlinks for the prior mods and just does it for the ones it had to double-check. This has become a major roadblock for installing larger packs with hundreds of mods (i.e. All the Magic: Spellbound 2,2,2).

**Comment by cdbbnnyCode** [comment]
Can verify. I don't know how this went unnoticed for as long as it did.

**Comment by cdbbnnyCode** [comment]
Fixed in v2.2.1-beta.
