### ISSUE TITLE
Can't install Better Minecraft

### ISSUE THREAD

**Issue by sukulent** [cdbbnnyCode/modpack-installer#14]
When I try running 'python install.py --manual BetterMCv12.zip' it fails with

Traceback (most recent call last):
  File "install.py", line 9, in <module>
    import forge_install
  File "/home/sukulent/.minecraft/mods/modpack-installer-2.2.1-beta/forge_install.py", line 29
    print("^ ", end="", flush=True)
                   ^
SyntaxError: invalid syntax

I am running old debian buster, if you want any other details, I am happy to provide them.
I want to install the fabric 1.18.2 version of Better Minecraft

**Comment by cdbbnnyCode** [comment]
You're using Python 2 (which was the default `python` on Debian until fairly recently afaik). This script uses Python 3. Try `python3 install.py ...`. If that doesn't work, make sure you have python3 installed.
