### ISSUE TITLE
404 error trying to download Forge

### ISSUE THREAD

**Issue by nhansendev** [cdbbnnyCode/modpack-installer#16]
It looks like the auto-generated URL format doesn't work for this specific version of Forge (MC 1.7.10).

Manually navigated to get this working link:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar

Auto-generated, non-working link (404 error):
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614/forge-1.7.10-10.13.4.1614-installer.jar

The modpack causing this issue is [here](https://www.curseforge.com/minecraft/modpacks/decimation-realistic-zombie-apocalypse-modpack/files/3151401).

I was able to successfully install a different modpack with a different version of Forge.

**Comment by cdbbnnyCode** [comment]
Hmm, that's interesting. Since there may be more versions that do this, I'll have to add in some additional logic to try the alternate URL if the first one fails.

Also, I should add a link to LexManos's Patreon since this code bypasses the adfly links...

**Comment by cdbbnnyCode** [comment]
Fixed in [7691391](https://github.com/cdbbnnyCode/modpack-installer/commit/76913913654f0ee36c13a9e63d8db70a2833d562)
