### ISSUE TITLE
Name or service not known addons-ecs.forgesvc.net

### ISSUE THREAD

**Issue by nogasgofast** [cdbbnnyCode/modpack-installer#24]
I can see the url in the mod_download.py file but when i use whatsmydns.net to lookup this name 
it has no A records or AAAA records in DNS.

Reference: 
https://www.whatsmydns.net/#A/addons-ecs.forgesvc.net
https://www.whatsmydns.net/#AAAA/addons-ecs.forgesvc.net

Although the domains does exist:
https://www.whatsmydns.net/#NS/forgesvc.net

**Comment by cdbbnnyCode** [comment]
Make sure you're using the latest version (2.3.0). CF changed their API a while back and I did make an update; however, I don't think I tagged a release for it, so feel free to just clone from the master branch directly.
