### ISSUE TITLE
Every modpack crashes with same 404 error code.

### ISSUE THREAD

**Issue by Warentan** [cdbbnnyCode/modpack-installer#33]
Every modpack that i've tried to run with this program has crashed with the same code. Code 6, and looking into the log, I get "[Warning: 2023-08-09 21:33:50.505880528: NetQueue.cpp(124)] Action https://launchercontent.mojang.com/ failed in response handler. response code: 404 - error string: ' "
I don't know what this means, but I assume it is caused by the modpack installer itself.

**Comment by cdbbnnyCode** [comment]
That sounds like the launcher can't download a file that the mod loader needs. Which modpacks are you trying to install?

**Comment by Warentan** [comment]
> 

Nevermind. It would seem that my 1.12.2 forge installation is corrupted and tries to contact a non-existent mojang link. I will fix this later.

On other versions it works fine.

**Comment by cdbbnnyCode** [comment]
That was what I was trying to figure out. Maybe try deleting the 1.12.2 Forge install from your `.minecraft/versions` and reinstalling it?

If that doesn't work, then install the latest 1.12.2 Forge (manually) and change the modpack installation in the launcher to use that version.

The installer script currently downloads the exact version of Forge/Fabric specified by the pack's manifest file, which might be way out of date for some modpacks. I should probably change it to use the latest available Forge version instead.

**Comment by cdbbnnyCode** [comment]
Closing because this issue is probably solved and there are no other reports of similar issues.
