### ISSUE TITLE
Unknown file type shaders

### ISSUE THREAD

**Issue by medfield** [cdbbnnyCode/modpack-installer#35]
Ive used your scripts to install All the Mods(9) in the past

when I go to installing the current version 
https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4769854

it grabs all of the mods except four, of which a manual download works just fine

but then the script ends with 

Finding files in /home/c/Downloads...
/home/c/Downloads/entityculling-forge-1.6.2-mc1.20.1.jar
/home/c/Downloads/totw_modded-1.0.1-1.20.1.jar
/home/c/Downloads/moreoverlays-1.22.1-mc1.20.jar
/home/c/Downloads/Structory_1.20.1_v1.3.2.jar
Linking mods
Unknown file type shaders

which in turn causes the game to not fully load with an Exit code of 1.

In the modlist there are two shader packs

[Complementary Shaders - Unbound (by EminGTR)](https://www.curseforge.com/minecraft/shaders/complementary-unbound)
[Complementary Shaders - Reimagined (by EminGTR)](https://www.curseforge.com/minecraft/shaders/complementary-reimagined)

both of which can install, I am just not sure why the script is ending in this error.

**Comment by cdbbnnyCode** [comment]
Shader packs are new in CurseForge, so this script doesn't know what to do with them.

I will put together a proper solution, but in the meantime, you can delete the `sys.exit(1)` line from around line 336 in `install.py`, which will allow it to finish linking and skip the shader packs. Then, you can install the shader packs manually.

**Comment by medfield** [comment]
The fix works, thank you for the quick response.
