### ISSUE TITLE
Cannot continue with install

### ISSUE THREAD

**Issue by spenkluker645** [cdbbnnyCode/modpack-installer#37]
Just asks me for a download directory, which is correct, but when i press Enter it just asks again.

**Comment by spenkluker645** [comment]
Edited the py to fix it myself.

**Comment by cdbbnnyCode** [comment]
Can you provide some detail on what you changed, or submit a pull request? Others might have the same issue.

**Comment by spenkluker645** [comment]
It was an issue on my end. I downloaded an outdated version by accident

**Comment by cdbbnnyCode** [comment]
Makes sense, thanks.
