### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Rushmore75** [cdbbnnyCode/modpack-installer#4]
I am working on a similar project but in java. I was wondering, how did you find the urls you are using for installing the mods?

**Comment by cdbbnnyCode** [comment]
I can't remember exactly what reference I used (in fact, when searching for it, it seems to have been deleted) but if you search the internet for "curseforge API" you should get some helpful resources.

Hope that helps; sorry I can't find the original reference (I remember it was pretty useful!)
