### ISSUE TITLE
Only file in modpack folder is "modConfig.json"

### ISSUE THREAD

**Issue by SampoPro** [cdbbnnyCode/modpack-installer#40]
The version of modpack-installer i´m using is 2.3.4
When i try to install a modpack it fails with the error "Forge installation not found.
Expected to find a directory named **1.20.1-forge-47.1.3 in /home/sampo/.minecraft/versions**
If a similarly named directory was created in the expected folder, please submit a
bug report."
And there´s a **folder named "1.20.1-forge-47.1.39" in "/home/sampo/.minecraft/versions".**
There´s a the modpack folder and instance in the minecraft launcher but the only file in the modpack folder is "[modConfig.json](https://github.com/cdbbnnyCode/modpack-installer/files/13256092/modConfig.json)"

**Comment by cdbbnnyCode** [comment]
Forge might have changed something about their installer for newer versions. I will check if this is the case.

Also, is the modpack trying to use Forge version `47.1.3` or `47.1.39`?

If you can provide the name of the modpack, that would be appreciated.

**Comment by SampoPro** [comment]
The modpack is called "Chosen´s Modded Adventure"
The manifest.json of the modpack says **forge-47.1.3**
Here´s the [curseforge link](https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure) if it´s needed 

Edit:When i try to install it the modpack instance is **"forge-47.1.3"** but it only installs **"forge-47.1.39"**

Edit2:The modpack folder just has some empty folders and **no mods folder**

**Comment by cdbbnnyCode** [comment]
It looks like the Forge version detection regex was a bit too permissive. Should be fixed in f6aa4ea.
