### ISSUE TITLE
Distribution Toggle Issue

### ISSUE THREAD

**Issue by medfield** [cdbbnnyCode/modpack-installer#42]
I looked through the closed issues and I don't believe anything pertains to this.  The Manual Download links that came up for BMC4 all worked, they Download to the directory just fine and none respond with a 404.  The only file that gives me issues after Download is the following file.  

* https://legacy.curseforge.com/minecraft/texture-packs/created-storage-network/download/4630227 (Created Simple Storage 1.3.zip)

'Created Simple Storage 1.3.zip'

The zip is pulled from curseforge, straight into the Download directory, but the install script just wont recognize it.  The zip isn't corrupted it opens and extracts manually.  Is the file name the problem?

**Comment by cdbbnnyCode** [comment]
I imagine it's having trouble because it's a resource pack and not a mod file. In the vast majority of cases, only mods have the distribution toggle turned off, so it's fairly likely I never set it up to handle other file types.

**Comment by cdbbnnyCode** [comment]
This is most likely because CF is inconsistent about how it handles files with spaces in them. For mod jars, it converts all spaces to '+', but apparently it doesn't do this for other files.

**Comment by cdbbnnyCode** [comment]
Should be fixed in 479bdc0.
