### ISSUE TITLE
[Debian Linux] Installing mods manually doesn't work properly.

### ISSUE THREAD

**Issue by TH3C4V** [cdbbnnyCode/modpack-installer#43]
The files the installer wants are in my downloads folder but it refuses to move on.

Modpack: Prominence II
Mods in question:
Aquamarae 6.jar "https://mediafilez.forgecdn.net/files/4656/204/Aquamirae%206.jar"
Enhanced Boss Bars "https://mediafilez.forgecdn.net/files/4592/221/%5B1.3%5D%20Enhanced%20Boss%20Bars.zip"

**Comment by cdbbnnyCode** [comment]
This looks like the same issue as #42, which should be fixed in the latest commit.
