### ISSUE TITLE
Script not working with Forge 1.16.5

### ISSUE THREAD

**Issue by KaanTheLinuxUser1** [cdbbnnyCode/modpack-installer#6]
I tried both manual and auto installing. They returned with Error code:200.
`
[pack data already unzipped]
[minecraft dir already created]
Installing modloader
Exception in thread "main" java.lang.ClassNotFoundException: com.google.common.base.Predicate
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at ForgeHack.main(ForgeHack.java:51)
ERROR: Forge did not install correctly!
`

But same modpack with FABRIC installed and no error outputs. 

And one question more: 

How can I use this installed modpack with custom Minecraft Launcher? I don't use Minecraft Launcher, so I don't know how to add this mod.

**Comment by cdbbnnyCode** [comment]
That error message should only show up when auto-installation is being performed. Are you sure you're setting the manual flag properly? It should be `--manual`

**Comment by cdbbnnyCode** [comment]
About the custom launcher, you should be able to use it if you can point it to a different `.minecraft` directory.

**Comment by KaanTheLinuxUser** [comment]
> That error message should only show up when auto-installation is being performed. Are you sure you're setting the manual flag properly? It should be `--manual`

It shows error output too. 
`python install.py --manual Better+Minecraft+\[FORGE\]+v37.zip 
[pack data already unzipped]
[minecraft dir already created]
Installing modloader
Downloading https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-installer.jar
Status: 200
JVM info: AdoptOpenJDK - 1.8.0_292 - 25.292-b10
java.net.preferIPv4Stack=true
Found java version 1.8.0_292
Extracting json
Considering minecraft client jar
Downloading libraries
Considering library net.minecraftforge:forge:1.16.5-36.2.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-util:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.1
  File exists: Checksum validated.
Considering library cpw.mods:modlauncher:8.0.9
  File exists: Checksum validated.
Considering library cpw.mods:grossjava9hacks:1.3.3
  File exists: Checksum validated.
Considering library net.minecraftforge:accesstransformers:3.0.1
  File exists: Checksum validated.
Considering library org.antlr:antlr4-runtime:4.9.1
  File exists: Checksum validated.
Considering library net.minecraftforge:eventbus:4.0.0
  File exists: Checksum validated.
Considering library net.minecraftforge:forgespi:3.2.0
  File exists: Checksum validated.
Considering library net.minecraftforge:coremods:4.0.6
  File exists: Checksum validated.
Considering library net.minecraftforge:unsafe:0.2.0
  File exists: Checksum validated.
Considering library com.electronwill.night-config:core:3.6.3
  File exists: Checksum validated.
Considering library com.electronwill.night-config:toml:3.6.3
  File exists: Checksum validated.
Considering library org.jline:jline:3.12.1
  File exists: Checksum validated.
Considering library org.apache.maven:maven-artifact:3.6.3
  File exists: Checksum validated.
Considering library net.jodah:typetools:0.8.3
  File exists: Checksum validated.
Considering library org.apache.logging.log4j:log4j-api:2.11.2
  File exists: Checksum validated.
Considering library org.apache.logging.log4j:log4j-core:2.11.2
  File exists: Checksum validated.
Considering library net.minecrell:terminalconsoleappender:1.2.0
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:5.0.4
  File exists: Checksum validated.
Considering library org.spongepowered:mixin:0.8.2
  File exists: Checksum validated.
Considering library net.minecraftforge:nashorn-core-compat:15.1.1.1
  File exists: Checksum validated.
Considering library com.github.jponge:lzma-java:1.3
  File exists: Checksum validated.
Considering library com.google.code.findbugs:jsr305:3.0.2
  File exists: Checksum validated.
Considering library com.google.code.gson:gson:2.8.7
  File exists: Checksum validated.
Considering library com.google.errorprone:error_prone_annotations:2.1.3
  File exists: Checksum validated.
Considering library com.google.guava:guava:20.0
  File exists: Checksum validated.
Considering library com.google.guava:guava:25.1-jre
  File exists: Checksum validated.
Considering library com.google.j2objc:j2objc-annotations:1.1
  File exists: Checksum validated.
Considering library com.nothome:javaxdelta:2.0.1
  File exists: Checksum validated.
Considering library com.opencsv:opencsv:4.4
  File exists: Checksum validated.
Considering library commons-beanutils:commons-beanutils:1.9.3
  File exists: Checksum validated.
Considering library commons-collections:commons-collections:3.2.2
  File exists: Checksum validated.
Considering library commons-io:commons-io:2.4
  File exists: Checksum validated.
Considering library commons-logging:commons-logging:1.2
  File exists: Checksum validated.
Considering library de.oceanlabs.mcp:mcp_config:1.16.5-20210115.111550@zip
  File exists: Checksum validated.
Considering library de.siegmar:fastcsv:2.0.0
  File exists: Checksum validated.
Considering library net.md-5:SpecialSource:1.10.0
  File exists: Checksum validated.
Considering library net.md-5:SpecialSource:1.8.5
  File exists: Checksum validated.
Considering library net.minecraftforge:binarypatcher:1.0.12
  File exists: Checksum validated.
Considering library net.minecraftforge:forge:1.16.5-36.2.2:universal
  File exists: Checksum validated.
Considering library net.minecraftforge:installertools:1.2.6
  File exists: Checksum validated.
Considering library net.minecraftforge:jarsplitter:1.1.4
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.3
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:4.9
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:5.0.4
  File exists: Checksum validated.
Considering library net.sf.opencsv:opencsv:2.3
  File exists: Checksum validated.
Considering library org.apache.commons:commons-collections4:4.2
  File exists: Checksum validated.
Considering library org.apache.commons:commons-lang3:3.8.1
  File exists: Checksum validated.
Considering library org.apache.commons:commons-text:1.3
  File exists: Checksum validated.
Considering library org.checkerframework:checker-qual:2.0.0
  File exists: Checksum validated.
Considering library org.codehaus.mojo:animal-sniffer-annotations:1.14
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.1
  File exists: Checksum validated.
Considering library trove:trove:1.0.2
  File exists: Checksum validated.
Created Temporary Directory: /tmp/forge_installer815546488918409701
  Extracting: /data/client.lzma
Building Processors
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /home/kaan/.minecraft/libraries/net/minecraftforge/installertools/1.2.6/installertools-1.2.6.jar
    /home/kaan/.minecraft/libraries/net/md-5/SpecialSource/1.10.0/SpecialSource-1.10.0.jar
    /home/kaan/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /home/kaan/.minecraft/libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /home/kaan/.minecraft/libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /home/kaan/.minecraft/libraries/net/minecraftforge/srgutils/0.4.3/srgutils-0.4.3.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
    /home/kaan/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /home/kaan/.minecraft/libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
    /home/kaan/.minecraft/libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /home/kaan/.minecraft/libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /home/kaan/.minecraft/libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /home/kaan/.minecraft/libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /home/kaan/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /home/kaan/.minecraft/libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, MCP_DATA, --input, /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip, --output, /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550-mappings.txt, --key, mappings
Task: MCP_DATA
Input:  /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip
Output: /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550-mappings.txt
Key:    mappings
Extracting: config/joined.tsrg
===============================================================================
  Cache: 
    /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-slim.jar Validated: 045d6edac8fe1b004e159c49704b5b729f551079
    /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-extra.jar Validated: 4aef4168f94d97bc73bf510213b2518942f931d1
  Cache Hit!
===============================================================================
  MainClass: net.md_5.specialsource.SpecialSource
  Classpath:
    /home/kaan/.minecraft/libraries/net/md-5/SpecialSource/1.8.5/SpecialSource-1.8.5.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-commons/6.1.1/asm-commons-6.1.1.jar
    /home/kaan/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.jar
    /home/kaan/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /home/kaan/.minecraft/libraries/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-analysis/6.1.1/asm-analysis-6.1.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-tree/6.1.1/asm-tree-6.1.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar
  Args: --in-jar, /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-slim.jar, --out-jar, /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-srg.jar, --srg-in, /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550-mappings.txt
Loading mappings
Loading mappings...  0%
Loading mappings... 10%
Loading mappings... 20%
Loading mappings... 30%
Loading mappings... 40%
Loading mappings... 50%
0 packages, 5447 classes, 21481 fields, 38359 methods
Remapping final jar
Remapping jar...  0%
Remapping jar... 10%
Remapping jar... 20%
Remapping jar... 30%
Remapping jar... 40%
Remapping jar... 50%
Remapping jar... 60%
Remapping jar... 70%
Remapping jar... 80%
Remapping jar... 90%
Remapping jar... 100%
===============================================================================
  Cache: 
    /home/kaan/.minecraft/libraries/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-client.jar Validated: 4cc9054a9a751a224aee90cf4294ea238d438d8e
  Cache Hit!
Injecting profile
Finished!
ERROR: Forge did not install correctly!
`

**Comment by KaanTheLinuxUser** [comment]
> About the custom launcher, you should be able to use it if you can point it to a different `.minecraft` directory.

I'm using TLauncher for its own preinstalled Forge and Fabric mods. And I added this args. Changed version to 1.17.1 Fabric and not working.
![2021-09-19_13-09](https://user-images.githubusercontent.com/64315521/133921870-8401d88c-7b7f-4b5d-8724-63435267d814.png)

**Comment by KaanTheLinuxUser1** [comment]
> About the custom launcher, you should be able to use it if you can point it to a different `.minecraft` directory.

I'm using TLauncher for its own preinstalled Forge and Fabric mods. And I added this args. Changed version to 1.17.1 Fabric and not working.
![2021-09-19_13-09](https://user-images.githubusercontent.com/90931651/133921967-6d1327a8-63f7-479e-98dd-68e7406bf9e1.png)

**Comment by KaanTheLinuxUser1** [comment]
> That error message should only show up when auto-installation is being performed. Are you sure you're setting the manual flag properly? It should be `--manual`

It shows error output too.

```
`python install.py `--manual` `Better+Minecraft+\[FORGE\]+v37.zip` 
`[pack data already unzipped]`
`[minecraft` dir already created]
`Installing` `modloader`
`Downloading` `https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-installer.jar`
`Status:` `200`
JVM info: AdoptOpenJDK - 1.8.0_292 - 25.292-b10
java.net.preferIPv4Stack=true
Found java version 1.8.0_292
Extracting json
Considering minecraft client jar
Downloading libraries
Considering library net.minecraftforge:forge:1.16.5-36.2.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-util:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.1
  File exists: Checksum validated.
Considering library cpw.mods:modlauncher:8.0.9
  File exists: Checksum validated.
Considering library cpw.mods:grossjava9hacks:1.3.3
  File exists: Checksum validated.
Considering library net.minecraftforge:accesstransformers:3.0.1
  File exists: Checksum validated.
Considering library org.antlr:antlr4-runtime:4.9.1
  File exists: Checksum validated.
Considering library net.minecraftforge:eventbus:4.0.0
  File exists: Checksum validated.
Considering library net.minecraftforge:forgespi:3.2.0
  File exists: Checksum validated.
Considering library net.minecraftforge:coremods:4.0.6
  File exists: Checksum validated.
Considering library net.minecraftforge:unsafe:0.2.0
  File exists: Checksum validated.
Considering library com.electronwill.night-config:core:3.6.3
  File exists: Checksum validated.
Considering library com.electronwill.night-config:toml:3.6.3
  File exists: Checksum validated.
Considering library org.jline:jline:3.12.1
  File exists: Checksum validated.
Considering library org.apache.maven:maven-artifact:3.6.3
  File exists: Checksum validated.
Considering library net.jodah:typetools:0.8.3
  File exists: Checksum validated.
Considering library org.apache.logging.log4j:log4j-api:2.11.2
  File exists: Checksum validated.
Considering library org.apache.logging.log4j:log4j-core:2.11.2
  File exists: Checksum validated.
Considering library net.minecrell:terminalconsoleappender:1.2.0
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:5.0.4
  File exists: Checksum validated.
Considering library org.spongepowered:mixin:0.8.2
  File exists: Checksum validated.
Considering library net.minecraftforge:nashorn-core-compat:15.1.1.1
  File exists: Checksum validated.
Considering library com.github.jponge:lzma-java:1.3
  File exists: Checksum validated.
Considering library com.google.code.findbugs:jsr305:3.0.2
  File exists: Checksum validated.
Considering library com.google.code.gson:gson:2.8.7
  File exists: Checksum validated.
Considering library com.google.errorprone:error_prone_annotations:2.1.3
  File exists: Checksum validated.
Considering library com.google.guava:guava:20.0
  File exists: Checksum validated.
Considering library com.google.guava:guava:25.1-jre
  File exists: Checksum validated.
Considering library com.google.j2objc:j2objc-annotations:1.1
  File exists: Checksum validated.
Considering library com.nothome:javaxdelta:2.0.1
  File exists: Checksum validated.
Considering library com.opencsv:opencsv:4.4
  File exists: Checksum validated.
Considering library commons-beanutils:commons-beanutils:1.9.3
  File exists: Checksum validated.
Considering library commons-collections:commons-collections:3.2.2
  File exists: Checksum validated.
Considering library commons-io:commons-io:2.4
  File exists: Checksum validated.
Considering library commons-logging:commons-logging:1.2
  File exists: Checksum validated.
Considering library de.oceanlabs.mcp:mcp_config:1.16.5-20210115.111550@zip
  File exists: Checksum validated.
Considering library de.siegmar:fastcsv:2.0.0
  File exists: Checksum validated.
Considering library net.md-5:SpecialSource:1.10.0
  File exists: Checksum validated.
Considering library net.md-5:SpecialSource:1.8.5
  File exists: Checksum validated.
Considering library net.minecraftforge:binarypatcher:1.0.12
  File exists: Checksum validated.
Considering library net.minecraftforge:forge:1.16.5-36.2.2:universal
  File exists: Checksum validated.
Considering library net.minecraftforge:installertools:1.2.6
  File exists: Checksum validated.
Considering library net.minecraftforge:jarsplitter:1.1.4
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.3
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:4.9
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:5.0.4
  File exists: Checksum validated.
Considering library net.sf.opencsv:opencsv:2.3
  File exists: Checksum validated.
Considering library org.apache.commons:commons-collections4:4.2
  File exists: Checksum validated.
Considering library org.apache.commons:commons-lang3:3.8.1
  File exists: Checksum validated.
Considering library org.apache.commons:commons-text:1.3
  File exists: Checksum validated.
Considering library org.checkerframework:checker-qual:2.0.0
  File exists: Checksum validated.
Considering library org.codehaus.mojo:animal-sniffer-annotations:1.14
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:6.1.1
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.1
  File exists: Checksum validated.
Considering library trove:trove:1.0.2
  File exists: Checksum validated.
Created Temporary Directory: /tmp/forge_installer815546488918409701
  Extracting: /data/client.lzma
Building Processors
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /home/kaan/.minecraft/libraries/net/minecraftforge/installertools/1.2.6/installertools-1.2.6.jar
    /home/kaan/.minecraft/libraries/net/md-5/SpecialSource/1.10.0/SpecialSource-1.10.0.jar
    /home/kaan/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /home/kaan/.minecraft/libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /home/kaan/.minecraft/libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /home/kaan/.minecraft/libraries/net/minecraftforge/srgutils/0.4.3/srgutils-0.4.3.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
    /home/kaan/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /home/kaan/.minecraft/libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
    /home/kaan/.minecraft/libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /home/kaan/.minecraft/libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /home/kaan/.minecraft/libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /home/kaan/.minecraft/libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /home/kaan/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /home/kaan/.minecraft/libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, MCP_DATA, --input, /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip, --output, /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550-mappings.txt, --key, mappings
Task: MCP_DATA
Input:  /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550.zip
Output: /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550-mappings.txt
Key:    mappings
Extracting: config/joined.tsrg
===============================================================================
  Cache: 
    /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-slim.jar Validated: 045d6edac8fe1b004e159c49704b5b729f551079
    /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-extra.jar Validated: 4aef4168f94d97bc73bf510213b2518942f931d1
  Cache Hit!
===============================================================================
  MainClass: net.md_5.specialsource.SpecialSource
  Classpath:
    /home/kaan/.minecraft/libraries/net/md-5/SpecialSource/1.8.5/SpecialSource-1.8.5.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-commons/6.1.1/asm-commons-6.1.1.jar
    /home/kaan/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.jar
    /home/kaan/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /home/kaan/.minecraft/libraries/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-analysis/6.1.1/asm-analysis-6.1.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm-tree/6.1.1/asm-tree-6.1.1.jar
    /home/kaan/.minecraft/libraries/org/ow2/asm/asm/6.1.1/asm-6.1.1.jar
  Args: --in-jar, /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-slim.jar, --out-jar, /home/kaan/.minecraft/libraries/net/minecraft/client/1.16.5-20210115.111550/client-1.16.5-20210115.111550-srg.jar, --srg-in, /home/kaan/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.16.5-20210115.111550/mcp_config-1.16.5-20210115.111550-mappings.txt
Loading mappings
Loading mappings...  0%
Loading mappings... 10%
Loading mappings... 20%
Loading mappings... 30%
Loading mappings... 40%
Loading mappings... 50%
0 packages, 5447 classes, 21481 fields, 38359 methods
Remapping final jar
Remapping jar...  0%
Remapping jar... 10%
Remapping jar... 20%
Remapping jar... 30%
Remapping jar... 40%
Remapping jar... 50%
Remapping jar... 60%
Remapping jar... 70%
Remapping jar... 80%
Remapping jar... 90%
Remapping jar... 100%
===============================================================================
  Cache: 
    /home/kaan/.minecraft/libraries/net/minecraftforge/forge/1.16.5-36.2.2/forge-1.16.5-36.2.2-client.jar Validated: 4cc9054a9a751a224aee90cf4294ea238d438d8e
  Cache Hit!
Injecting profile
Finished!
ERROR: Forge did not install correctly!
```

**Comment by cdbbnnyCode** [comment]
When you install manually, you have to set the manual installer's `.minecraft` directory to the modpack's `.minecraft` directory, i.e. `/path/to/modpack-installer/packs/Better+Minecraft+[FORGE]+v37/.minecraft`. I will document this better for future reference.

The installer will not install modpacks to your main `.minecraft` directory. If you would like that to be a feature, please put that in a new feature request issue.

**Comment by Onering20** [comment]
Can you leave the in the line `/path/to/modpack-installer/packs/%MODPACK%/.minecraft` in the README I just did a fresh install and I did not understand the structure of how this works but this line cleared up my confusion

**Comment by cdbbnnyCode** [comment]
I will add that to the README, especially since I'm seeing more issues related to that coming up.
